# Linguagem de Programação para Ciência de Dados I: Fundamentos do Python 
## Exercícios sobre Fundamentos de Python

## Prof. Mauro Ribeiro 
## Monitor: Lucas Horinouchi

O objetivo desse notebook é ajudar na fixação dos conteúdos que passamos nas aulas de Fundamentos de Python.

Para começar a responder a lista faça uma cópia deste notebook para o seu google drive. 

Opcional para correção: Após terminar envie a sua lista com permissão de edição no slack para o canal #notebooks.

### Variáveis

[Documentação](https://docs.python.org/3/tutorial/introduction.html) inicial do python

In [ ]:
# Exercício 1 - Declare uma variavel chamada "a" e atribua o valor 10 a ela
a = 10

In [ ]:
# Exercício 2 - Imprime essa variavel que você acabou de criar
print(a)

10


In [ ]:
# Exercício 3 - Crie uma outra variavel "b" que recebe o valor de "a" so que como string
b = str(a)

'10'

In [ ]:
# Exercício 4 - Combine sua variavel "b" a variavel abaixo para obter a string "Hello 10" em uma variavel "d"
c = "Hello "
d = c + " " + b

In [ ]:
# Exercício 5 - Imprima a variável "d"
print(d)

Hello  10


### Strings

In [ ]:
my_str = 'Insira uma frase aqui!'

In [ ]:
# Exercício 6 - Substitua a exclamação da frase por uma interrogação
# (Dica: A funcão altera inplace ou retorna uma copia modificada?)
outra_str = my_str.replace("!","?")
outra_str #a função retorna uma cópia modificada e não modifica a string original

'Insira uma frase aqui!'

In [ ]:
# Exercício 7 - Crie uma lista "my_words" com cada palavra da frase como elemento da lista
my_words = my_str.split()
my_words

['Insira', 'uma', 'frase', 'aqui!']

### Listas
Além de olhar a documentação também faça pesquisas procurando por termos desconhecidos pesquisas em inglês costumam retornar mais resultador, porém também existem resultados em portugues. [Exemplo](https://letmegooglethat.com/?q=python+listas)

In [ ]:
lista = [1, 23, 31, 40, 56, 16]

In [ ]:
# Exercício 8 - Faça um for que imprima cada elemento da lista "lista" (Lembre-se que o for em python é um for each)
for x in lista:
  print(x)

1
23
31
40
56
16


In [ ]:
# Exercício 9 - Faça um for que imprima o dobro de cada elemento da lista "lista" 
for x in lista:
  print(x*2)

2
46
62
80
112
32


In [ ]:
# Exercício 10 - Gere uma lista chamada "dobro" com o dobro de cada elemento de "lista" usando list comprehension
dobro = [x*2 for x in lista]

[2, 46, 62, 80, 112, 32]

In [ ]:
# Exercício 11 - Crie uma nova lista chamada "pares"
# Faça um for que itetere sobre a lista "lista" e para cada elemento impar coloque ele no fim da lista "pares"
# Imprima a lista "pares"
pares=[]
for x in lista:
  if x % 2 == 0:
    pares.insert(0,x)
  else:
    pares.append(x)
pares

[16, 56, 40, 1, 23, 31]

In [ ]:
lista2 = ['oi', 2, 2.5, 'top', 'python', 45]

In [ ]:
# Exercício 12 - Faça um for pela "lista2" e imprima todos os elementos que são strings (Dica: pesquise pela função type())
for x in lista2:
  if type(x) == str:
    print(x)
  

oi
top
python


#### Indexando

In [ ]:
my_list = [0, 10, 20, 30, 40, 50, 60, 70]

In [ ]:
# Exercício 13 - Selecione o ultimo elemento da lista
my_list[-1]

70

In [ ]:
# Exercício 14 - Selecione do primeiro até o 4 elemento da lista
my_list[:4]

[0, 10, 20, 30]

In [ ]:
# Exercício 15 - Selecione do segundo elemento da lista até o quinto
my_list[1:5]

[10, 20, 30, 40]

In [ ]:
# Exercício 16 - Selecione do primeiro elemento da lista até o penultimo
my_list[:-1]

[0, 10, 20, 30, 40, 50, 60]

### Dicionários

In [ ]:
lista = ['a', 'a', 'b', 'a', 'c', 'd', 'e', 'b', 'b', 'c']

In [ ]:
# Exercício 17 - Crie um dicionario que contenha a contagem de cada elemento do vetor
my_dict = {x:lista.count(x) for x in lista}


In [ ]:
print(my_dict)

{'a': 3, 'b': 3, 'c': 2, 'd': 1, 'e': 1}


### Funções

In [ ]:
# Exercício 18 - Crie uma função soma_elementos() que recebe uma lista e retorna a soma de todos os seus elementos
def soma_elementos(lista):
    return sum(lista)

In [ ]:
soma_elementos([1, 2, 3, 4, 5])

15

In [ ]:
soma_elementos([-1, 5, 7, -2])

9

In [ ]:
# Exercício 19 - Crie uma função produto_escalar() que recebe duas listas de tamanho igual e calcula o produto escalar entre elas
# Dica: Utilize a função zip
def produto_escalar(lista1,lista2):
  return sum([x*y for x,y in zip(lista1,lista2)])

In [ ]:
produto_escalar([1, 2, 3], [0, 4, 7])

29

In [ ]:
produto_escalar([10, 20, 40, 1], [23, 4, 2, 1])

391

In [ ]:
# Exercício 20 - Crie uma função par_ou_impar() que recebe um numero n é para cada numero de 1 a n imprime o numero
# seguido de par ou impar, dependendo do que ele seja. Caso o usuário não coloque nada n deve valer 20
# Exemplo: par_ou_impar(4)
#   1 Impar
#   2 Par
#   3 Impar
#   4 Par
def par_ou_impar(n=20):
  for x in range(1,n+1):
    if x % 2 == 0:
      print(str(x) + ' Par')
    else:
      print(str(x) + ' Impar')

In [ ]:
par_ou_impar(15)

1 Impar
2 Par
3 Impar
4 Par
5 Impar
6 Par
7 Impar
8 Par
9 Impar
10 Par
11 Impar
12 Par
13 Impar
14 Par
15 Impar


In [ ]:
par_ou_impar()

1 Impar
2 Par
3 Impar
4 Par
5 Impar
6 Par
7 Impar
8 Par
9 Impar
10 Par
11 Impar
12 Par
13 Impar
14 Par
15 Impar
16 Par
17 Impar
18 Par
19 Impar
20 Par


In [ ]:
# Exercício 21 - Crie uma função diga_indice() que recebe uma lista e imprime o indice de cada elemento e em seguida 
# o proprio elemento
# Exemplo: diga_indice(['oi', 'tudo', 'bem'])
#    0 oi
#    1 tudo
#    2 bem
# (DICA: Pesquise pela função enumerate)
def diga_indice(lista):
  for indice, elemento in enumerate(lista):
    print(indice,elemento)

In [ ]:
diga_indice(['1', '2', '3'])

0 1
1 2
2 3


In [ ]:
diga_indice(['a', 'b', 'c', 'd', 'e'])

0 a
1 b
2 c
3 d
4 e


## Numpy

O elemento central do numpy são os arrays, então aqui vamos treinar muitas coisas sobre eles

[Documentação do numpy](https://numpy.org/devdocs/reference/index.html)

Além de olhar a documentação também faça pesquisas procurando por termos desconhecidos pesquisas em inglês costumam retornar mais resultador, porém também existem resultados em portugues. [Exemplo](https://letmegooglethat.com/?q=numpy+shape)

In [ ]:
# Importando a biblioteca
import numpy as np

### Arrays

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

c = np.zeros((3,4))

In [ ]:
# Exercício 22 - Pense em qual é a shape de cada um dos arrays acima
# Depois de pensar imprima cada um deles para conferir sua resposta
print(a.shape)
print(b.shape)
print(c.shape)

(7,)
(2, 4)
(3, 4)


In [ ]:
# Exercício 23 - Crie um array de uma dimensão com 20 elementos inteiros aletórios entre 0 e 23
arr = np.random.randint(23, size=(20,))
arr

array([ 3,  7,  6,  3, 10, 11,  8, 19, 20,  9, 15,  4,  5, 12, 16, 10, 20,
       12, 10, 11])

In [ ]:
# Exercício 24 - Crie um array de uns com shape (4, 5)
uns = np.ones((4,5))
uns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Exercício 25 - Crie um array shape (4, 2) onde cada entrada vale 77
# (Dica: Talvez vc tenha que usar uma multiplicação)
arr = np.full((4, 2), 77)
arr

array([[77, 77],
       [77, 77],
       [77, 77],
       [77, 77]])

In [ ]:
# Exercício 26 - Gere um array chamado my_sequence com os numeros 0, 10, 20, 30, ..., 90, 100]
my_sequence = np.arange(0,110,10)
my_sequence

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### Indexando

In [ ]:
my_array = np.random.randint(50, size=(15,))
print(my_array)

[34 49 43  1 19  9 20 38  4 28 38 33 28 36  6]


In [ ]:
# Exercício 27 - Selecione todos os elementos entre o quinto e o decimo primeiro (intervalo fechado)
my_array[4:11]

array([19,  9, 20, 38,  4, 28, 38])

In [ ]:
# Exercício 28 - Selecione todos os elementos maiores que 20
my_array[my_array>20]

array([34, 49, 43, 38, 28, 38, 33, 28, 36])

In [ ]:
my_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

In [ ]:
# Exercício 29 - Selecione o elemento na primeira linha da terceira coluna
my_matrix[0,2]

3

In [ ]:
# Exercício 30 - Selecione o elemento na primeira linha da ultima coluna
my_matrix[0,-1]

4

In [ ]:
# Exercício 31 - Selecione os elementos da matriz para obter o seguinte
# [[6, 7],
#  [10, 11]]
my_matrix[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [ ]:
# Exercício 32 - Selecione os elementos da matriz para obter o seguinte
# [[2, 3, 4],
#  [6, 7, 8]]
my_matrix[0:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
# Exercício 33 - Selecione os elementos da ultima coluna inteira
my_matrix[:,-1]

array([ 4,  8, 12, 16])

In [ ]:
# Exercício 34 - Selecione os elementos da 2a linha inteira
my_matrix[1,:]

array([5, 6, 7, 8])

# Nova seção

### Operações

In [ ]:
my_array = np.random.randint(10, size=(5,))
print(my_array)

[1 3 9 3 0]


In [ ]:
# Exercício 35 - Some 10 a todos os elementos de my_array
my_array + 10

array([12, 18, 11, 10, 13])

In [ ]:
# Exercício 36 - Multiplique todos os elementos de my_array por 4
my_array * 4

array([ 8, 32,  4,  0, 12])

In [ ]:
# Exercício 37 - Obtenha a soma de todos os elementos de my_array
np.sum(my_array)

15

In [ ]:
# Exercício 38 - Obtenha a média de todos os elementos de my_array
np.mean(my_array)

3.0

In [ ]:
# Exercício 39 - Obtenha o indice do maior elemento de my_array
#my_array.where(max(my_array))
np.argwhere(my_array == max(my_array))[0][0]

2

In [ ]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(5,))
print(my_array, '\n')
print(my_other_array)

[2 2 9 2 5] 

[0 9 3 7 5]


In [ ]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[0 0 2 4 5] 

[[5 1 7 4 3]
 [2 3 0 4 2]
 [4 9 8 8 9]
 [4 8 3 8 1]
 [2 4 3 2 3]
 [5 1 5 0 3]
 [4 6 9 6 7]
 [0 4 9 6 5]
 [9 0 2 7 1]
 [5 9 4 7 1]]


In [ ]:
# Exercício 40 - Some my_array elemento por elemento em cada linha de my_other_array
my_array + my_other_array

array([[ 5,  1,  9,  8,  8],
       [ 2,  3,  2,  8,  7],
       [ 4,  9, 10, 12, 14],
       [ 4,  8,  5, 12,  6],
       [ 2,  4,  5,  6,  8],
       [ 5,  1,  7,  4,  8],
       [ 4,  6, 11, 10, 12],
       [ 0,  4, 11, 10, 10],
       [ 9,  0,  4, 11,  6],
       [ 5,  9,  6, 11,  6]])

In [ ]:
my_array = np.random.randint(10, size=(5,4))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[[7 0 2 6]
 [8 4 6 3]
 [1 3 8 4]
 [1 6 2 7]
 [7 9 7 4]] 

[[8 5 4 0 0]
 [8 0 9 2 7]
 [6 2 0 7 2]
 [0 9 9 2 4]
 [3 4 8 7 9]
 [8 9 8 7 2]
 [7 7 7 6 9]
 [5 0 5 8 3]
 [3 6 2 2 9]
 [3 6 5 1 2]]


In [ ]:
# Exercício 41 - Faça a multiplicação entre my_other_array e my_array
np.dot(my_other_array,my_array)

array([[100,  32,  78,  79],
       [116, 102, 141, 126],
       [ 79,  68,  52,  99],
       [111, 111, 158,  93],
       [131, 163, 171, 147],
       [157, 120, 162, 164],
       [181, 166, 187, 169],
       [ 69,  90,  87, 118],
       [136, 123, 125,  94],
       [ 89,  63,  98,  71]])

In [ ]:
# Exercício 42 - Descubra a soma dos valores de cada linha de my_other_array
# (Dica: Pesquise sobre o atributo axis da função de soma)
np.sum(my_other_array, axis=1)

array([17, 26, 17, 24, 31, 34, 36, 21, 22, 17])

In [ ]:
my_array = np.random.randint(10, size=(5,4))
print(my_array)

[[6 0 5 8]
 [5 2 5 3]
 [9 5 2 7]
 [5 6 4 3]
 [9 9 2 5]]


In [ ]:
# Exercício 43 - Usando reshape transforme a matriz acima em um vetor (Concatendo a linha de baixo na de cima)
np.reshape(my_array,my_array.size)

array([6, 0, 5, 8, 5, 2, 5, 3, 9, 5, 2, 7, 5, 6, 4, 3, 9, 9, 2, 5])

In [ ]:
np.array([[ 0,  1,  2,  3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12, 13, 14, 15]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
# Exercício 44 - Gere a array anterior usando np.arange e a função reshape
np.reshape(np.arange(0, 16, 1),(2,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])